/****************************************************************************
 *
 *      DirectInput keyboard scan codes
 *
 ****************************************************************************/
;const int  DIK_ESCAPE          =0x01
;const int  DIK_1               =0x02
;const int  DIK_2               =0x03
;const int  DIK_3               =0x04
;const int  DIK_4               =0x05
;const int  DIK_5               =0x06
;const int  DIK_6               =0x07
;const int  DIK_7               =0x08
;const int  DIK_8               =0x09
;const int  DIK_9               =0x0A
;const int  DIK_0               =0x0B
;const int  DIK_MINUS           =0x0C    /* - on main keyboard */
;const int  DIK_EQUALS          =0x0D
;const int  DIK_BACK            =0x0E    /* backspace */
;const int  DIK_TAB             =0x0F
;const int  DIK_Q               =0x10
;const int  DIK_W               =0x11
;const int  DIK_E               =0x12
;const int  DIK_R               =0x13
;const int  DIK_T               =0x14
;const int  DIK_Y               =0x15
;const int  DIK_U               =0x16
;const int  DIK_I               =0x17
;const int  DIK_O               =0x18
;const int  DIK_P               =0x19
;const int  DIK_LBRACKET        =0x1A
;const int  DIK_RBRACKET        =0x1B
;const int  DIK_RETURN          =0x1C    /* Enter on main keyboard */
;const int  DIK_LCONTROL        =0x1D
;const int  DIK_A               =0x1E
;const int  DIK_S               =0x1F
;const int  DIK_D               =0x20
;const int  DIK_F               =0x21
;const int  DIK_G               =0x22
;const int  DIK_H               =0x23
;const int  DIK_J               =0x24
;const int  DIK_K               =0x25
;const int  DIK_L               =0x26
;const int  DIK_SEMICOLON       =0x27
;const int  DIK_APOSTROPHE      =0x28
;const int  DIK_GRAVE           =0x29    /* accent grave */
;const int  DIK_LSHIFT          =0x2A
;const int  DIK_BACKSLASH       =0x2B
;const int  DIK_Z               =0x2C
;const int  DIK_X               =0x2D
;const int  DIK_C               =0x2E
;const int  DIK_V               =0x2F
;const int  DIK_B               =0x30
;const int  DIK_N               =0x31
;const int  DIK_M               =0x32
;const int  DIK_COMMA           =0x33
;const int  DIK_PERIOD          =0x34    /* . on main keyboard */
;const int  DIK_SLASH           =0x35    /* / on main keyboard */
;const int  DIK_RSHIFT          =0x36
;const int  DIK_MULTIPLY        =0x37    /* * on numeric keypad */
;const int  DIK_LMENU           =0x38    /* left Alt */
;const int  DIK_SPACE           =0x39
;const int  DIK_CAPITAL         =0x3A
;const int  DIK_F1              =0x3B
;const int  DIK_F2              =0x3C
;const int  DIK_F3              =0x3D
;const int  DIK_F4              =0x3E
;const int  DIK_F5              =0x3F
;const int  DIK_F6              =0x40
;const int  DIK_F7              =0x41
;const int  DIK_F8              =0x42
;const int  DIK_F9              =0x43
;const int  DIK_F10             =0x44
;const int  DIK_NUMLOCK         =0x45
;const int  DIK_SCROLL          =0x46    /* Scroll Lock */
;const int  DIK_NUMPAD7         =0x47
;const int  DIK_NUMPAD8         =0x48
;const int  DIK_NUMPAD9         =0x49
;const int  DIK_SUBTRACT        =0x4A    /* - on numeric keypad */
;const int  DIK_NUMPAD4         =0x4B
;const int  DIK_NUMPAD5         =0x4C
;const int  DIK_NUMPAD6         =0x4D
;const int  DIK_ADD             =0x4E    /* + on numeric keypad */
;const int  DIK_NUMPAD1         =0x4F
;const int  DIK_NUMPAD2         =0x50
;const int  DIK_NUMPAD3         =0x51
;const int  DIK_NUMPAD0         =0x52
;const int  DIK_DECIMAL         =0x53    /* . on numeric keypad */
;const int  DIK_F11             =0x57
;const int  DIK_F12             =0x58
;const int  DIK_F13             =0x64    /*                     (NEC PC98) */
;const int  DIK_F14             =0x65    /*                     (NEC PC98) */
;const int  DIK_F15             =0x66    /*                     (NEC PC98) */
;const int  DIK_KANA            =0x70    /* (Japanese keyboard)            */
;const int  DIK_ABNT_C1         =0x73    /* / ? on Portugese (Brazilian) keyboards */
;const int  DIK_CONVERT         =0x79    /* (Japanese keyboard)            */
;const int  DIK_NOCONVERT       =0x7B    /* (Japanese keyboard)            */
;const int  DIK_YEN             =0x7D    /* (Japanese keyboard)            */
;const int  DIK_ABNT_C2         =0x7E    /* Numpad . on Portugese (Brazilian) keyboards */
;const int  DIK_NUMPADEQUALS    =0x8D    /* = on numeric keypad (NEC PC98) */
;const int  DIK_PREVTRACK       =0x90    /* Previous Track (DIK_CIRCUMFLEX on Japanese keyboard) */
;const int  DIK_AT              =0x91    /*                     (NEC PC98) */
;const int  DIK_COLON           =0x92    /*                     (NEC PC98) */
;const int  DIK_UNDERLINE       =0x93    /*                     (NEC PC98) */
;const int  DIK_KANJI           =0x94    /* (Japanese keyboard)            */
;const int  DIK_STOP            =0x95    /*                     (NEC PC98) */
;const int  DIK_AX              =0x96    /*                     (Japan AX) */
;const int  DIK_UNLABELED       =0x97    /*                        (J3100) */
;const int  DIK_NEXTTRACK       =0x99    /* Next Track */
;const int  DIK_NUMPADENTER     =0x9C    /* Enter on numeric keypad */
;const int  DIK_RCONTROL        =0x9D
;const int  DIK_MUTE            =0xA0    /* Mute */
;const int  DIK_CALCULATOR      =0xA1    /* Calculator */
;const int  DIK_PLAYPAUSE       =0xA2    /* Play / Pause */
;const int  DIK_MEDIASTOP       =0xA4    /* Media Stop */
;const int  DIK_VOLUMEDOWN      =0xAE    /* Volume - */
;const int  DIK_VOLUMEUP        =0xB0    /* Volume + */
;const int  DIK_WEBHOME         =0xB2    /* Web home */
;const int  DIK_NUMPADCOMMA     =0xB3    /* , on numeric keypad (NEC PC98) */
;const int  DIK_DIVIDE          =0xB5    /* / on numeric keypad */
;const int  DIK_SYSRQ           =0xB7
;const int  DIK_RMENU           =0xB8    /* right Alt */
;const int  DIK_PAUSE           =0xC5    /* Pause */
;const int  DIK_HOME            =0xC7    /* Home on arrow keypad */
;const int  DIK_UP              =0xC8    /* UpArrow on arrow keypad */
;const int  DIK_PRIOR           =0xC9    /* PgUp on arrow keypad */
;const int  DIK_LEFT            =0xCB    /* LeftArrow on arrow keypad */
;const int  DIK_RIGHT           =0xCD    /* RightArrow on arrow keypad */
;const int  DIK_END             =0xCF    /* End on arrow keypad */
;const int  DIK_DOWN            =0xD0    /* DownArrow on arrow keypad */
;const int  DIK_NEXT            =0xD1    /* PgDn on arrow keypad */
;const int  DIK_INSERT          =0xD2    /* Insert on arrow keypad */
;const int  DIK_DELETE          =0xD3    /* Delete on arrow keypad */
;const int  DIK_LWIN            =0xDB    /* Left Windows key */
;const int  DIK_RWIN            =0xDC    /* Right Windows key */
;const int  DIK_APPS            =0xDD    /* AppMenu key */
;const int  DIK_POWER           =0xDE    /* System Power */
;const int  DIK_SLEEP           =0xDF    /* System Sleep */
;const int  DIK_WAKE            =0xE3    /* System Wake */
;const int  DIK_WEBSEARCH       =0xE5    /* Web Search */
;const int  DIK_WEBFAVORITES    =0xE6    /* Web Favorites */
;const int  DIK_WEBREFRESH      =0xE7    /* Web Refresh */
;const int  DIK_WEBSTOP         =0xE8    /* Web Stop */
;const int  DIK_WEBFORWARD      =0xE9    /* Web Forward */
;const int  DIK_WEBBACK         =0xEA    /* Web Back */
;const int  DIK_MYCOMPUTER      =0xEB    /* My Computer */
;const int  DIK_MAIL            =0xEC    /* Mail */
;const int  DIK_MEDIASELECT     =0xED    /* Media Select */
;